### ISSUE TITLE
Crash TtnAzureBridge.exe

### ISSUE THREAD

**Issue by thomasvoorend** [sandervandevelde/Techdays2017#1]
TtnAzureBridge crashes on startup after "Whitelist is empty"

![image](https://user-images.githubusercontent.com/32485864/31126487-35c51cec-a84c-11e7-81fe-75f0a94ef20d.png)

**Comment by sandervandevelde** [comment]
This could be an issue caused by a 'non open' internet eg. MQTT ports are not available. Please check the ability to deploy it correctly using a web job (Webjob.md) or in a non-office (just at home) environment.

**Comment by MarieGlas** [comment]
![screen shot 2017-10-03 at 22 06 18](https://user-images.githubusercontent.com/32485908/31146722-cdf99444-a887-11e7-96bf-b7767cae85ea.png)

**Comment by thomasvoorend** [comment]
Thanks Sander! It worked
