### ISSUE TITLE
wrongly placed forward slash

### ISSUE THREAD

**Issue by longlifebattery** [sandervandevelde/Techdays2017#2]
At point 5 by Create a Device Identity.

</dependency>
   <groupId>com.microsoft.azure.sdk.iot</groupId>
   <artifactId>iot-service-client</artifactId>
   <version>1.2.17</version>
</dependency>

must be:

<dependency>
   <groupId>com.microsoft.azure.sdk.iot</groupId>
   <artifactId>iot-service-client</artifactId>
   <version>1.2.17</version>
</dependency>

Just a simple forward slash removal.

**Comment by sandervandevelde** [comment]
Please elaborate, I see no differences in your text and which file are we talking about? Or better, this is a perfect chance for a Pull Request
